name: sweetviz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - pip:
      - sweetviz
